### DISCUSSION TITLE
阿里ack部署illa-builder挂载持久卷的正确姿势？

### DISCUSSION THREAD

**Discussion by Kain-90** [illacloud/illa-builder#1694] [中文支持 Chinese Support]
如下操作，也有对应的PVC和PV，部署成功，但是每次重新部署，数据就不见了。
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ops 
  name: illa-builder
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: illa-builder
  serviceName: illa-builder
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: illa-builder
    spec:
      containers:
      - image: illasoft/illa-builder:v2.4.0
        imagePullPolicy: Always
        name: illa-builder
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        env:
        - name: ILLA_DEPLOY_MODE
          value: "self-host"
        volumeMounts:
          - name: illa-data
            mountPath: /opt/illa/database:rw
      volumes:
        - persistentVolumeClaim:
            claimName: illa-data
          name: illa-data

```

**Comment by karminski** [comment]
@Kain-90 hi, 请使用latest镜像, v2.4.0的挂在地址不在/opt/illa/database, 默认是需要手动指定postgres的存储位置决定的.

**Reply by Kain-90** [reply]
最新镜像的挂载path我这样写对吗？
```
        volumeMounts:
          - name: illa-data
            mountPath: /opt/illa/database
      volumes:
        - persistentVolumeClaim:
            claimName: illa-data
          name: illa-data
```
