### DISCUSSION TITLE
Listen to 127.0.0.1 only

### DISCUSSION THREAD

**Discussion by ssfufu** [illacloud/illa-builder#1994] [Q&A] [answered]
Hello, I have created and deployed an Illa builder instance with Illa CLI with that command:
`illa deploy --self --port=2022`

But when I look at the `docker ps` output, it tells me that the container is listening to every IP at that given port. The issue here is that I use a reverse proxy (nginx in my case) and that it is set to redirect traffic going to illa.domain.com to 127.0.0.1.
Is there any way to make the container only listen to 127.0.0.1 ?

Thank you in advance.

ps: here is the docker ps output for the network:
`0.0.0.0:2022->2022/tcp, 5432/tcp`

**Comment by karminski** [comment, marked as answer]
@ssfufu hi, you can use docker command to do it. like: 
```
mkdir -p ~/illa/database; mkdir -p ~/illa/drive; 
docker run -d --name illa_builder -p127.0.0.1:2022:2022 -v ~/illa/database:/opt/illa/database -v ~/illa/drive:/opt/illa/drive illasoft/illa-builder:latest 
```

**Reply by ssfufu** [reply]
Well that was much easier than I expected. Thank you and have a nice day!

**Comment by ml-airflow** [comment]
For docker-compose; 

```
  illa-builder:
    restart: always
    image: "illasoft/illa-builder:latest"
    ports:
      - "127.0.0.1:2022:2022"
    volumes:
      - ./illadb:/opt/illa/database:rw
      - ./illadrive:/opt/illa/drive:rw
 ```
